### ISSUE TITLE
ProjectionManager vs PatientManagement

### ISSUE THREAD

**Issue by bhaidar** [mat-mcloughlin/PatientMangement#3]
Hi Mathew,
I am following your session on CQRS and Event Sourcing. A great resource for a beginner like me in this field.

In the PatientManagement project, you are basically storing events in the Event Store.

In the ProjectionManager project, are you hooking into the Event Store to know when a new event is added in order to generate the data for Patients? Is that what's happening in this demo? 

Also, in the Projection project, you are creating and saving Patient objects, what does that have to do with projection? Maybe I am missing something in here.

Thanks

**Comment by mat-mcloughlin** [comment]
The intention with the projection manager is that it plays through all the events in the event store and generates the patient data off the back of it. That it's self is the projection
